/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import clases.ConnToMysql;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario PM
 */
public class Formulario extends javax.swing.JFrame {
    ConnToMysql conn;
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtidLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombreLibro = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtEjemplares = new javax.swing.JTextField();
        btnInsertarLibro = new javax.swing.JButton();
        btnConsultarLibro = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtNombreCategoria = new javax.swing.JTextField();
        txtidCategoria = new javax.swing.JTextField();
        btnConsultarCategoria = new javax.swing.JButton();
        btnInsertarCategoria = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jchkLibro = new javax.swing.JCheckBox();
        jchkCategoria = new javax.swing.JCheckBox();
        btnEliminarLibro = new javax.swing.JButton();
        btnEliminarCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Libro");

        txtidLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidLibroActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        jLabel3.setText("Nombre");

        jLabel4.setText("Autor");

        jLabel5.setText("Editorial");

        jLabel6.setText("Ejemplares");

        txtNombreLibro.setEnabled(false);

        txtAutor.setEnabled(false);

        txtEditorial.setEnabled(false);
        txtEditorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditorialActionPerformed(evt);
            }
        });

        txtEjemplares.setEnabled(false);

        btnInsertarLibro.setText("Insertar");
        btnInsertarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarLibroActionPerformed(evt);
            }
        });

        btnConsultarLibro.setText("Consultar");
        btnConsultarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarLibroActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Categoria");

        jLabel8.setText("ID");

        jLabel9.setText("Nombre");

        jLabel10.setText("Descripcion");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcion);

        txtNombreCategoria.setAutoscrolls(false);
        txtNombreCategoria.setEnabled(false);

        btnConsultarCategoria.setText("Consultar");
        btnConsultarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCategoriaActionPerformed(evt);
            }
        });

        btnInsertarCategoria.setText("Insertar");
        btnInsertarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarCategoriaActionPerformed(evt);
            }
        });

        jLabel11.setText("Categoria (ID)");

        txtCategoria.setEnabled(false);

        jchkLibro.setText("Modificar");
        jchkLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkLibroActionPerformed(evt);
            }
        });

        jchkCategoria.setText("Modificar");
        jchkCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCategoriaActionPerformed(evt);
            }
        });

        btnEliminarLibro.setText("Eliminar");
        btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLibroActionPerformed(evt);
            }
        });

        btnEliminarCategoria.setText("Eliminar");
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertarLibro)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(txtEjemplares, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidLibro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarLibro)
                                    .addComponent(jchkLibro)
                                    .addComponent(btnEliminarLibro))))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jchkCategoria))
                            .addComponent(btnInsertarCategoria)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtidCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnConsultarCategoria)
                                    .addComponent(btnEliminarCategoria))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnConsultarLibro)
                    .addComponent(jLabel8)
                    .addComponent(txtidCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarCategoria))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(btnEliminarLibro))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(jchkLibro))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtEjemplares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jchkCategoria))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertarLibro)
                            .addComponent(btnInsertarCategoria)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidLibroActionPerformed

    private void txtEditorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditorialActionPerformed

    private void btnConsultarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarLibroActionPerformed
        String query = "SELECT * FROM libro WHERE idLibro =  " + Integer.parseInt(txtidLibro.getText());
        try{
        conn = new ConnToMysql();
        Connection conexion = conn.getConnection();
        Statement st = conexion.createStatement();
        ResultSet rs = st.executeQuery(query);
        while(rs.next()){
            txtNombreLibro.setText(rs.getString("nombreLibro"));
            txtAutor.setText(rs.getString("autorLibro"));
            txtEditorial.setText(rs.getString("editorial"));
            txtEjemplares.setText(rs.getString("ejemplares"));
            txtCategoria.setText(rs.getString("idCategoria"));
        }
        conn = null;
        System.out.println("Conexión Terminada");
        }
        catch(SQLException e){
            System.out.println("Error SQL: "+ e);
            JOptionPane.showMessageDialog(null, "Ingresa un ID valido\n" + "Error: " + e);

        }
        catch(NumberFormatException er){
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + er);

        }
    }//GEN-LAST:event_btnConsultarLibroActionPerformed

    private void btnInsertarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarLibroActionPerformed
        String query = "INSERT INTO libro VALUES(?,?,?,?,?,?)";
        
        try{
        conn = new ConnToMysql();
        Connection conexion = conn.getConnection();
        PreparedStatement prest = conexion.prepareStatement(query); 
        
        int idLibro = Integer.parseInt(txtidLibro.getText());
        prest.setInt(1, idLibro);
        
        String nombreLibro = txtNombreLibro.getText();
        prest.setString(2, nombreLibro);
        
        String autor = txtAutor.getText();
        prest.setString(3, autor);
        
        String editorial = txtEditorial.getText();
        prest.setString(4, editorial);
        
        int ejemplares = Integer.parseInt(txtEjemplares.getText());
        prest.setInt(5, ejemplares);
        
        int categoriaid = Integer.parseInt(txtCategoria.getText());
        prest.setInt(6, categoriaid);
        
        prest.execute();
        
        System.out.println("Dato ingresado con exito!");
        
        conexion.close();
        System.out.println("Conexión Terminada");
        }
        catch(SQLException e){
            System.out.println("Error SQL: "+ e);
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + e);

        }
        catch(NumberFormatException er){
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + er);

        }
     }//GEN-LAST:event_btnInsertarLibroActionPerformed

    private void btnInsertarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarCategoriaActionPerformed
        String query = "INSERT INTO categoria VALUES(?,?,?)";
        
        try{
        conn = new ConnToMysql();
        Connection conexion = conn.getConnection();
        PreparedStatement prest = conexion.prepareStatement(query); 
        
        int idCategoria = Integer.parseInt(txtidCategoria.getText());
        prest.setInt(1, idCategoria);
        
        String nombreCategoria = txtNombreCategoria.getText();
        prest.setString(2, nombreCategoria);
        
        String descripcion = txtDescripcion.getText();
        prest.setString(3, descripcion);
        
        prest.execute();
        
        System.out.println("Dato ingresado con exito!");
        
        conexion.close();
        System.out.println("Conexión Terminada");
        }
        catch(SQLException e){
            System.out.println("Error SQL: "+ e);
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + e);
            
        }
        catch(NumberFormatException er){
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + er);

        }
    }//GEN-LAST:event_btnInsertarCategoriaActionPerformed

    private void btnConsultarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCategoriaActionPerformed
        String query = "SELECT * FROM categoria WHERE idCategoria =  " + Integer.parseInt(txtidCategoria.getText());
        try{
        conn = new ConnToMysql();
        Connection conexion = conn.getConnection();
        Statement st = conexion.createStatement();
        ResultSet rs = st.executeQuery(query);
        while(rs.next()){
            txtNombreCategoria.setText(rs.getString("nombreCategoria"));
            txtDescripcion.setText(rs.getString("descripcionCategoria"));
        }
        conn = null;
        System.out.println("Conexión Terminada");
        }
        catch(SQLException e){
            System.out.println("Error SQL: "+ e);
            JOptionPane.showMessageDialog(null, "Ingresa un ID valido\n" + "Error: " + e);
        }
        catch(NumberFormatException er){
            System.out.println("Error SQL: "+ er);            
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + er);

        }
    }//GEN-LAST:event_btnConsultarCategoriaActionPerformed

    private void jchkLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkLibroActionPerformed
        if (jchkLibro.isSelected()) {
                txtNombreLibro.setEnabled(true);
                txtAutor.setEnabled(true);
                txtEditorial.setEnabled(true);
                txtEjemplares.setEnabled(true);
                txtCategoria.setEnabled(true);
        }
        else {
                txtNombreLibro.setEnabled(false);
                txtAutor.setEnabled(false);
                txtEditorial.setEnabled(false);
                txtEjemplares.setEnabled(false);
                txtCategoria.setEnabled(false);            
        }
    }//GEN-LAST:event_jchkLibroActionPerformed

    private void jchkCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCategoriaActionPerformed
        if (jchkCategoria.isSelected()) { 
            txtNombreCategoria.setEnabled(true);
            txtDescripcion.setEnabled(true);
        }
        else {
            txtNombreCategoria.setEnabled(false);
            txtDescripcion.setEnabled(false);
        }
    }//GEN-LAST:event_jchkCategoriaActionPerformed

    private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroActionPerformed
        String query = "DELETE FROM libro WHERE idLibro = " + Integer.parseInt(txtidLibro.getText());
        
        try{
        conn = new ConnToMysql();
        Connection conexion = conn.getConnection();
        PreparedStatement prest = conexion.prepareStatement(query); 
        
        prest.executeUpdate();
        
        System.out.println("Dato Eliminado con exito!");
        JOptionPane.showMessageDialog(null, "Dato eliminado correctamente");

        
        conexion.close();
        System.out.println("Conexión Terminada");
        }
        catch(SQLException e){
            System.out.println("Error SQL: "+ e);
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + e);
            
        }
        catch(NumberFormatException er){
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + er);

        }
    }//GEN-LAST:event_btnEliminarLibroActionPerformed

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        String query = "DELETE FROM categoria WHERE idCategoria = " + Integer.parseInt(txtidCategoria.getText());
        
        try{
        conn = new ConnToMysql();
        Connection conexion = conn.getConnection();
        PreparedStatement prest = conexion.prepareStatement(query); 
        
        prest.executeUpdate();
        
        System.out.println("Dato Eliminado con exito!");
        JOptionPane.showMessageDialog(null, "Dato eliminado correctamente");

        
        conexion.close();
        System.out.println("Conexión Terminada");
        }
        catch(SQLException e){
            System.out.println("Error SQL: "+ e);
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + e);
            
        }
        catch(NumberFormatException er){
            JOptionPane.showMessageDialog(null, "Ingresa los datos correctamente\n" + "Error: " + er);

        }
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
                                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultarCategoria;
    private javax.swing.JButton btnConsultarLibro;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnEliminarLibro;
    private javax.swing.JButton btnInsertarCategoria;
    private javax.swing.JButton btnInsertarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox jchkCategoria;
    private javax.swing.JCheckBox jchkLibro;
    private static javax.swing.JTextField txtAutor;
    private static javax.swing.JTextField txtCategoria;
    private static javax.swing.JTextArea txtDescripcion;
    private static javax.swing.JTextField txtEditorial;
    private static javax.swing.JTextField txtEjemplares;
    private static javax.swing.JTextField txtNombreCategoria;
    private static javax.swing.JTextField txtNombreLibro;
    private static javax.swing.JTextField txtidCategoria;
    private static javax.swing.JTextField txtidLibro;
    // End of variables declaration//GEN-END:variables
}
